import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scroll-smooth`}
    >
      <body className="min-h-screen flex flex-col">
        <div className="relative">
        {/* Background layer */}
        <div className="absolute top-0 left-0 w-full h-full -z-10 bg-[url('/tree4-r.jpg')] bg-cover bg-top bg-no-repeat " />

        <Navbar />
        {children}
        </div>
        </body>

    </html>
  );
}
